### ISSUE TITLE
Create API for EN

### ISSUE THREAD

**Issue by zakiego** [zakiego/salin-abangku#21]
## Description

Type lang = "en" | "id"

From
https://salin-abangku.vercel.app/api/one
https://salin-abangku.vercel.app/api/all

To
https://salin-abangku.vercel.app/api/one?lang=en
https://salin-abangku.vercel.app/api/all?lang=en

Keep the default is ID

Data from [template.ts](./src/lib/template.ts)

<img width="701" alt="image" src="https://github.com/zakiego/salin-abangku/assets/78015359/70d7daa8-afa3-4e49-8535-1e41c75c2614">

**Comment by muhammadiqbalid83** [comment]
bisa kasih petunjuk mas? mengerjakannya gimana? jujur saya kebingungan.
