### ISSUE TITLE
Add API Link in Readme

### ISSUE THREAD

**Issue by zakiego** [zakiego/salin-abangku#22]
https://salin-abangku.vercel.app/api/one

https://salin-abangku.vercel.app/api/all

**Comment by muhammadiqbalid83** [comment]
ngambil API linknya dari mana mas?

**Comment by zakiego** [comment]
Maaf bang kurang jelas, sudah saya edit

Tinggal nambah link itu ke readme

**Comment by muhammadiqbalid83** [comment]
![kenapa](https://github.com/zakiego/salin-abangku/assets/121326593/9e7d50c4-8699-4da6-a7bf-b2e6cf39c039)

ini kenapa ya? ketika saya push dia tidak mau

**Comment by zakiego** [comment]
Solusi simpel:
1. Fork ulang (repo yang sekarang bisa dihapus)
2. Clone ke lokal
3. Edit
4. Push
5. Bikin PR

Solusi agak-agak:
1. Batalin commit terakhir (`git reset --soft HEAD~1`)
2. Hapus perubahan terakhir
3. Di https://github.com/muhammadiqbalid83/salin-abangku, cari tombol update upstream atau semacamnya (saya lupa)
4. Di lokal, `git pull`
5. Edit filenya
6. Push

**Comment by muhammadiqbalid83** [comment]
makasih mas
